# Generated by Django 6.0.4 on 2026-04-27 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula o NIT')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo o Razón Social')),
                ('telefono', models.CharField(max_length=20, verbose_name='Número de Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de Residencia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Cliente Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('placa', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Placa del Vehículo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca / Fabricante')),
                ('modelo', models.CharField(max_length=100, verbose_name='Línea o Modelo')),
                ('serial_motor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial del Motor')),
                ('serial_chasis', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial del Chasis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='motorcycles', to='customers.customer', verbose_name='Propietario del Vehículo')),
            ],
            options={
                'verbose_name': 'Motocicleta',
                'verbose_name_plural': 'Motocicletas',
                'ordering': ['-created_at'],
            },
        ),
    ]
